import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { HrPayrollLine, HrPayrollRun } from '@/lib/hr-types'

export function downloadPayslipPdf(opts: {
  run: HrPayrollRun
  line: HrPayrollLine
  filename?: string
}): void {
  const doc = new jsPDF()
  const margin = 14
  const pageW = doc.internal.pageSize.getWidth()

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('NWRMA — Payslip', margin, 20)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(`Period: ${opts.run.period}`, margin, 28)
  doc.text(`Employee: ${opts.line.employeeName ?? opts.line.employeeId}`, margin, 34)
  doc.text(`Number: ${opts.line.employeeNumber ?? '—'}`, margin, 40)
  doc.text(`Type: ${opts.line.lineType}`, margin, 46)

  autoTable(doc, {
    startY: 52,
    head: [['Item', 'Amount (SLE)']],
    body: [
      ['Gross', opts.line.gross.toFixed(2)],
      ['Allowances', opts.line.allowances.toFixed(2)],
      ['Overtime', opts.line.overtimeAmount.toFixed(2)],
      ['Deductions', `-${opts.line.deductions.toFixed(2)}`],
      [`Tax (${opts.run.defaultTaxRatePct}%)`, `-${opts.line.taxAmount.toFixed(2)}`],
      ['Net pay', opts.line.net.toFixed(2)],
    ],
    theme: 'striped',
    headStyles: { fillColor: [40, 167, 69] },
    margin: { left: margin, right: margin },
    tableWidth: pageW - margin * 2,
  })

  const finalY =
    (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 90
  doc.setFontSize(8)
  doc.setTextColor(102, 102, 102)
  doc.text('Generated by NWRMA ERP — HR & Admin', margin, finalY + 10)

  const name = (opts.line.employeeName ?? 'employee').replace(/[^\w-]+/g, '_')
  doc.save(opts.filename ?? `payslip-${opts.run.period}-${name}.pdf`)
}

export function downloadAllPayslipsForRun(
  run: HrPayrollRun,
  lines: HrPayrollLine[]
): void {
  for (const line of lines) {
    downloadPayslipPdf({ run, line })
  }
}
