import type {
  User,
  FiscalYear,
  ProgrammeBudgetLine,
  Requisition,
  RequisitionEvent,
  MonitoringStation,
  WaterLevelReading,
  GaugeOfficer,
  OfficerPayment,
  HydrologicalSettings,
  DrillingCompany,
  Borehole,
  LabRequest,
  Employee,
  LeaveRequest,
  Asset,
  BoreholeLicenseApplication,
  WaterQualityPublicCase,
  Notification,
  FloodIncident,
} from './types'
import { emptyDocumentMetaSlots } from '@/lib/borehole-licensing-documents'

/** Demo dataset for optional `POST /api/admin/seed-database` only — not loaded by the running app. */

// Current User (for demo - can be changed to test different roles)
export const currentUser: User = {
  id: 'user-001',
  email: 'admin@nwrma.gov.sl',
  name: 'Mohamed Kamara',
  role: 'hod',
  department: 'hr',
  status: 'active',
  createdAt: new Date('2023-01-15'),
}

// All Users
export const users: User[] = [
  currentUser,
  {
    id: 'user-002',
    email: 'dg@nwrma.gov.sl',
    name: 'Dr. Fatmata Sesay',
    role: 'dg',
    department: null,
    status: 'active',
    createdAt: new Date('2023-01-10'),
  },
  {
    id: 'user-003',
    email: 'hod.hydro@nwrma.gov.sl',
    name: 'Ibrahim Koroma',
    role: 'hod',
    department: 'hydrological',
    status: 'active',
    createdAt: new Date('2023-02-01'),
  },
  {
    id: 'user-004',
    email: 'hod.boreholes@nwrma.gov.sl',
    name: 'Aminata Bangura',
    role: 'hod',
    department: 'boreholes',
    status: 'active',
    createdAt: new Date('2023-02-01'),
  },
  {
    id: 'user-005',
    email: 'hod.wq@nwrma.gov.sl',
    name: 'Samuel Conteh',
    role: 'hod',
    department: 'hydrological',
    status: 'active',
    createdAt: new Date('2023-02-01'),
  },
  {
    id: 'user-006',
    email: 'hod.finance@nwrma.gov.sl',
    name: 'Mariama Jalloh',
    role: 'hod',
    department: 'financial',
    status: 'active',
    createdAt: new Date('2023-02-01'),
  },
  {
    id: 'user-007',
    email: 'hod.hr@nwrma.gov.sl',
    name: 'Abu Bakarr Turay',
    role: 'hod',
    department: 'hr',
    status: 'active',
    createdAt: new Date('2023-02-01'),
  },
  {
    id: 'user-008',
    email: 'staff.hydro@nwrma.gov.sl',
    name: 'Isatu Mansaray',
    role: 'staff',
    department: 'hydrological',
    status: 'active',
    createdAt: new Date('2023-03-15'),
  },
]

// Fiscal Years
export const fiscalYears: FiscalYear[] = [
  {
    id: 'fy-2024',
    label: 'FY 2024',
    start: new Date('2024-01-01'),
    end: new Date('2024-12-31'),
    isActive: true,
  },
  {
    id: 'fy-2023',
    label: 'FY 2023',
    start: new Date('2023-01-01'),
    end: new Date('2023-12-31'),
    isActive: false,
  },
]

// Budget Lines
export const budgetLines: ProgrammeBudgetLine[] = [
  {
    id: 'bl-001',
    fiscalYearId: 'fy-2024',
    department: 'hydrological',
    programmeCode: 'HYD-001',
    programmeName: 'Gauge Officer Program',
    allocatedAmount: 120000000,
    utilizedAmount: 42000000,
    currency: 'SLE',
  },
  {
    id: 'bl-002',
    fiscalYearId: 'fy-2024',
    department: 'hydrological',
    programmeCode: 'HYD-002',
    programmeName: 'Station Maintenance',
    allocatedAmount: 200000000,
    utilizedAmount: 80000000,
    currency: 'SLE',
  },
  {
    id: 'bl-003',
    fiscalYearId: 'fy-2024',
    department: 'boreholes',
    programmeCode: 'BH-001',
    programmeName: 'Borehole Registration & Licensing',
    allocatedAmount: 300000000,
    utilizedAmount: 150000000,
    currency: 'SLE',
  },
  {
    id: 'bl-004',
    fiscalYearId: 'fy-2024',
    department: 'hydrological',
    programmeCode: 'WQ-001',
    programmeName: 'Water Quality Testing Equipment',
    allocatedAmount: 85500000,
    utilizedAmount: 61100000,
    currency: 'SLE',
  },
  {
    id: 'bl-005',
    fiscalYearId: 'fy-2024',
    department: 'financial',
    programmeCode: 'FIN-001',
    programmeName: 'Field Station Maintenance',
    allocatedAmount: 250000000,
    utilizedAmount: 87500000,
    currency: 'SLE',
  },
  {
    id: 'bl-006',
    fiscalYearId: 'fy-2024',
    department: 'hr',
    programmeCode: 'HR-001',
    programmeName: 'ERP System Rollout',
    allocatedAmount: 45500000,
    utilizedAmount: 12000000,
    currency: 'SLE',
  },
]

// Requisitions
export const requisitions: Requisition[] = [
  {
    id: 'req-001',
    department: 'hydrological',
    requesterId: 'user-008',
    requesterName: 'Isatu Mansaray',
    hodUserId: 'user-003',
    amount: 15000000,
    currency: 'SLE',
    narrative: 'Purchase of water level sensors for Freetown monitoring stations',
    programmeBudgetLineId: 'bl-001',
    status: 'dg_review',
    financeNotes: 'Budget available. Recommend approval.',
    dgNotes: null,
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: 'req-002',
    department: 'boreholes',
    requesterId: 'user-004',
    requesterName: 'Aminata Bangura',
    hodUserId: null,
    amount: 8500000,
    currency: 'SLE',
    narrative: 'Field inspection vehicle fuel allocation for Q2',
    programmeBudgetLineId: 'bl-003',
    status: 'finance_review',
    financeNotes: null,
    dgNotes: null,
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-12'),
  },
  {
    id: 'req-003',
    department: 'hydrological',
    requesterId: 'user-005',
    requesterName: 'Samuel Conteh',
    hodUserId: null,
    amount: 25000000,
    currency: 'SLE',
    narrative: 'Laboratory reagents and testing equipment maintenance',
    programmeBudgetLineId: 'bl-004',
    status: 'approved',
    financeNotes: 'Approved. Critical for lab operations.',
    dgNotes: 'Approved. Priority item for public health.',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-28'),
  },
  {
    id: 'req-004',
    department: 'hr',
    requesterId: 'user-007',
    requesterName: 'Abu Bakarr Turay',
    hodUserId: null,
    amount: 5000000,
    currency: 'SLE',
    narrative: 'Staff training workshop on new ERP system',
    programmeBudgetLineId: 'bl-006',
    status: 'submitted',
    financeNotes: null,
    dgNotes: null,
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'req-005',
    department: 'hydrological',
    requesterId: 'user-003',
    requesterName: 'Ibrahim Koroma',
    hodUserId: null,
    amount: 12000000,
    currency: 'SLE',
    narrative: 'Emergency repair of damaged monitoring station at Rokel River',
    programmeBudgetLineId: 'bl-002',
    status: 'paid',
    financeNotes: 'Emergency approval granted.',
    dgNotes: 'Approved. Critical infrastructure.',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-02-01'),
  },
]

// Requisition Events
export const requisitionEvents: RequisitionEvent[] = [
  {
    id: 'evt-001',
    requisitionId: 'req-001',
    fromStatus: 'draft',
    toStatus: 'submitted',
    byUserId: 'user-008',
    byUserName: 'Isatu Mansaray',
    comment: 'Submitting for approval',
    createdAt: new Date('2024-03-01'),
  },
  {
    id: 'evt-002',
    requisitionId: 'req-001',
    fromStatus: 'submitted',
    toStatus: 'hod_review',
    byUserId: 'user-003',
    byUserName: 'Ibrahim Koroma',
    comment: 'Reviewed and forwarded to finance',
    createdAt: new Date('2024-03-02'),
  },
]

// Monitoring Stations
export const monitoringStations: MonitoringStation[] = [
  {
    id: 'sta-001',
    name: 'Freetown Central Station',
    code: 'FT-001',
    lat: 8.4657,
    lng: -13.2317,
    district: 'Western Area Urban',
    notes: 'Primary monitoring station for capital region',
    status: 'active',
    alertThresholdM: 3.8,
  },
  {
    id: 'sta-002',
    name: 'Rokel River Station',
    code: 'RK-001',
    lat: 8.8167,
    lng: -12.2000,
    district: 'Port Loko',
    notes: 'Major river monitoring point',
    status: 'active',
    alertThresholdM: 6.5,
  },
  {
    id: 'sta-003',
    name: 'Bo District Station',
    code: 'BO-001',
    lat: 7.9647,
    lng: -11.7383,
    district: 'Bo',
    notes: 'Southern region primary station',
    status: 'active',
    alertThresholdM: 2.2,
  },
  {
    id: 'sta-004',
    name: 'Kenema Station',
    code: 'KN-001',
    lat: 7.8767,
    lng: -11.1900,
    district: 'Kenema',
    notes: 'Eastern region monitoring',
    status: 'active',
    alertThresholdM: 5.5,
  },
  {
    id: 'sta-005',
    name: 'Makeni Station',
    code: 'MK-001',
    lat: 8.8833,
    lng: -12.0500,
    district: 'Bombali',
    notes: 'Northern region station',
    status: 'inactive',
    alertThresholdM: 4.2,
  },
]

export const floodIncidents: FloodIncident[] = [
  {
    id: 'fl-001',
    reportedAt: new Date('2024-03-10T06:30:00'),
    district: 'Port Loko',
    riverOrArea: 'Rokel River (upstream gauge network)',
    severity: 'warning',
    status: 'monitoring',
    summary: 'Rapid level rise after sustained rainfall; field teams verifying downstream communities.',
  },
  {
    id: 'fl-002',
    reportedAt: new Date('2024-03-12T14:00:00'),
    district: 'Western Area Rural',
    riverOrArea: 'Aberdeen Creek tidal influence',
    severity: 'watch',
    status: 'open',
    summary: 'Coastal surge watch aligned with high tides; public advisory issued.',
  },
  {
    id: 'fl-003',
    reportedAt: new Date('2024-02-20T09:15:00'),
    district: 'Bo',
    riverOrArea: 'Sewa River tributaries',
    severity: 'severe',
    status: 'closed',
    summary: 'Localized bank overflow; damages recorded; case closed after mitigation works.',
  },
]

export const gaugeOfficers: GaugeOfficer[] = [
  {
    id: 'go-001',
    fullName: 'Isatu Mansaray',
    phone: '+232 76 111223',
    linkedUserId: 'user-008',
    fieldAppKey: 'demo-field-officer-isatu',
  },
  {
    id: 'go-002',
    fullName: 'Ibrahim Koroma',
    phone: '+232 78 445566',
    linkedUserId: null,
    fieldAppKey: 'demo-field-officer-ibrahim',
  },
  {
    id: 'go-003',
    fullName: 'Amadu Bangura',
    phone: '+232 77 998877',
    linkedUserId: null,
    fieldAppKey: 'demo-field-officer-amadu',
  },
]

/** Default rate for incentive accrual (SLE per validated reading) */
export const hydrologicalSettings: HydrologicalSettings = {
  perReadingRateSle: 50_000,
  fieldAppKey: 'demo-field-app-key',
}

export const officerPaymentsSeed: OfficerPayment[] = [
  {
    id: 'pay-001',
    gaugeOfficerId: 'go-001',
    officerName: 'Isatu Mansaray',
    yearMonth: '2024-03',
    validSubmissions: 2,
    rateSle: hydrologicalSettings.perReadingRateSle,
    totalSle: 2 * hydrologicalSettings.perReadingRateSle,
    status: 'pending',
    submittedAt: null,
    approvedAt: null,
    disbursedAt: null,
    approvedByUserId: null,
    disbursedByUserId: null,
  },
  {
    id: 'pay-002',
    gaugeOfficerId: 'go-002',
    officerName: 'Ibrahim Koroma',
    yearMonth: '2024-03',
    validSubmissions: 1,
    rateSle: hydrologicalSettings.perReadingRateSle,
    totalSle: 1 * hydrologicalSettings.perReadingRateSle,
    status: 'submitted',
    submittedAt: new Date('2024-03-16T10:00:00'),
    approvedAt: null,
    disbursedAt: null,
    approvedByUserId: null,
    disbursedByUserId: null,
  },
  {
    id: 'pay-003',
    gaugeOfficerId: 'go-003',
    officerName: 'Amadu Bangura',
    yearMonth: '2024-02',
    validSubmissions: 3,
    rateSle: hydrologicalSettings.perReadingRateSle,
    totalSle: 3 * hydrologicalSettings.perReadingRateSle,
    status: 'disbursed',
    submittedAt: new Date('2024-02-28T09:00:00'),
    approvedAt: new Date('2024-03-01T14:00:00'),
    disbursedAt: new Date('2024-03-05T12:00:00'),
    approvedByUserId: 'user-002',
    disbursedByUserId: 'user-002',
  },
]

// Water Level Readings
export const waterLevelReadings: WaterLevelReading[] = [
  {
    id: 'rdg-001',
    stationId: 'sta-001',
    stationName: 'Freetown Central Station',
    officerName: 'Isatu Mansaray',
    phoneNumber: '+232 76 111223',
    gaugeOfficerId: 'go-001',
    hodValidation: 'valid',
    location: 'Lumley gauge house, Aberdeen Creek',
    measuredAt: new Date('2024-03-15T08:00:00'),
    levelM: 2.45,
    gpsLocation: '8.4521° N, 13.2897° W',
    gaugePhotoUrl: 'https://picsum.photos/seed/gauge1/120/120',
    qualityFlag: 'good',
    source: 'manual',
    createdBy: 'Isatu Mansaray',
    createdAt: new Date('2024-03-15T08:30:00'),
  },
  {
    id: 'rdg-002',
    stationId: 'sta-001',
    stationName: 'Freetown Central Station',
    officerName: 'Isatu Mansaray',
    phoneNumber: '+232 76 111223',
    gaugeOfficerId: 'go-001',
    hodValidation: 'valid',
    location: 'Lumley gauge house, Aberdeen Creek',
    measuredAt: new Date('2024-03-14T08:00:00'),
    levelM: 2.52,
    gpsLocation: '8.4520° N, 13.2896° W',
    gaugePhotoUrl: null,
    qualityFlag: 'good',
    source: 'manual',
    createdBy: 'Isatu Mansaray',
    createdAt: new Date('2024-03-14T08:30:00'),
  },
  {
    id: 'rdg-003',
    stationId: 'sta-002',
    stationName: 'Rokel River Station',
    officerName: 'Ibrahim Koroma',
    phoneNumber: '+232 78 445566',
    gaugeOfficerId: 'go-002',
    hodValidation: 'valid',
    location: 'Rokel River bridge downstream-left bank',
    measuredAt: new Date('2024-03-15T09:00:00'),
    levelM: 4.85,
    gpsLocation: '8.9456° N, 12.8422° W',
    gaugePhotoUrl: 'https://picsum.photos/seed/gauge3/120/120',
    qualityFlag: 'good',
    source: 'manual',
    createdBy: 'Ibrahim Koroma',
    createdAt: new Date('2024-03-15T09:30:00'),
  },
  {
    id: 'rdg-004',
    stationId: 'sta-003',
    stationName: 'Bo District Station',
    officerName: 'Amadu Bangura',
    phoneNumber: '+232 77 998877',
    gaugeOfficerId: 'go-003',
    hodValidation: 'pending',
    location: 'Bo township gauge — Sewa River reserve',
    measuredAt: new Date('2024-03-15T07:30:00'),
    levelM: 1.92,
    gpsLocation: '7.9647° N, 11.7389° W',
    gaugePhotoUrl: null,
    qualityFlag: 'suspect',
    source: 'manual',
    createdBy: 'Amadu Bangura',
    createdAt: new Date('2024-03-15T08:00:00'),
  },
]

// Drilling Companies
export const drillingCompanies: DrillingCompany[] = [
  {
    id: 'dc-001',
    name: 'Sierra Water Drilling Ltd',
    registrationNo: 'SL-DRL-2020-001',
    contacts: {
      phone: '+232 76 123456',
      email: 'info@sierrawater.sl',
      address: '15 Siaka Stevens Street, Freetown',
    },
    status: 'active',
    licenseExpiry: new Date('2025-12-31'),
  },
  {
    id: 'dc-002',
    name: 'African Groundwater Solutions',
    registrationNo: 'SL-DRL-2019-005',
    contacts: {
      phone: '+232 77 234567',
      email: 'contact@ags-sl.com',
      address: '8 Lumley Beach Road, Freetown',
    },
    status: 'active',
    licenseExpiry: new Date('2024-06-30'),
  },
  {
    id: 'dc-003',
    name: 'Community Borehole Services',
    registrationNo: 'SL-DRL-2021-012',
    contacts: {
      phone: '+232 78 345678',
      email: 'cbs@example.sl',
      address: '22 Main Street, Bo',
    },
    status: 'suspended',
    licenseExpiry: new Date('2024-03-31'),
  },
]

// Boreholes
export const boreholes: Borehole[] = [
  {
    id: 'bh-001',
    code: 'BH-FT-2024-001',
    district: 'Western Area Urban',
    region: 'Western',
    lat: 8.4750,
    lng: -13.2400,
    depthM: 45,
    purpose: 'Community water supply',
    ownerName: 'Freetown City Council',
    drillingCompanyId: 'dc-001',
    drillingCompanyName: 'Sierra Water Drilling Ltd',
    registryStatus: 'approved',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'bh-002',
    code: 'BH-BO-2024-002',
    district: 'Bo',
    region: 'Southern',
    lat: 7.9600,
    lng: -11.7400,
    depthM: 60,
    purpose: 'Agricultural irrigation',
    ownerName: 'Bo Agricultural Cooperative',
    drillingCompanyId: 'dc-002',
    drillingCompanyName: 'African Groundwater Solutions',
    registryStatus: 'approved',
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 'bh-003',
    code: 'BH-KN-2024-003',
    district: 'Kenema',
    region: 'Eastern',
    lat: 7.8800,
    lng: -11.2000,
    depthM: null,
    purpose: 'Hospital water supply',
    ownerName: 'Kenema Government Hospital',
    drillingCompanyId: null,
    drillingCompanyName: null,
    registryStatus: 'pending',
    createdAt: new Date('2024-03-01'),
  },
]

// Lab Requests
export const labRequests: LabRequest[] = [
  {
    id: 'lab-001',
    reference: 'WQ-2024-0001',
    publicCaseId: null,
    requesterName: 'Ministry of Health',
    requesterEmail: 'lab@moh.gov.sl',
    organisation: 'Government of Sierra Leone',
    siteAddress: 'Connaught Hospital, Freetown',
    testsRequested: ['pH', 'Turbidity', 'E. coli', 'Total Coliforms'],
    priority: 'urgent',
    status: 'testing',
    assignedToUserId: 'user-005',
    assignedToName: 'Samuel Conteh',
    receivedAt: new Date('2024-03-10'),
    completedAt: null,
    results: null,
  },
  {
    id: 'lab-002',
    reference: 'WQ-2024-0002',
    publicCaseId: 'wq-pub-001',
    requesterName: 'John Smith',
    requesterEmail: 'john.smith@example.com',
    organisation: 'Private Residence',
    siteAddress: '45 Hill Station, Freetown',
    testsRequested: ['pH', 'Turbidity', 'Iron', 'Manganese'],
    priority: 'normal',
    status: 'completed',
    assignedToUserId: 'user-005',
    assignedToName: 'Samuel Conteh',
    receivedAt: new Date('2024-03-05'),
    completedAt: new Date('2024-03-12'),
    results: { pH: 7.2, turbidity: 1.5, iron: 0.2, manganese: 0.05 },
  },
  {
    id: 'lab-003',
    reference: 'WQ-2024-0003',
    publicCaseId: null,
    requesterName: 'UNICEF Sierra Leone',
    requesterEmail: 'water@unicef.org',
    organisation: 'UNICEF',
    siteAddress: 'Multiple sites - Kono District',
    testsRequested: ['Full Panel', 'Heavy Metals', 'Microbial'],
    priority: 'critical',
    status: 'received',
    assignedToUserId: null,
    assignedToName: null,
    receivedAt: new Date('2024-03-14'),
    completedAt: null,
    results: null,
  },
]

// Employees
export const employees: Employee[] = [
  {
    id: 'emp-001',
    userId: 'user-001',
    fullName: 'Mohamed Kamara',
    title: 'HR & Admin Head of Department',
    department: 'hr',
    phone: '+232 76 111111',
    email: 'admin@nwrma.gov.sl',
    hiredAt: new Date('2023-01-15'),
    status: 'active',
  },
  {
    id: 'emp-002',
    userId: 'user-002',
    fullName: 'Dr. Fatmata Sesay',
    title: 'Director General',
    department: null,
    phone: '+232 76 222222',
    email: 'dg@nwrma.gov.sl',
    hiredAt: new Date('2022-06-01'),
    status: 'active',
  },
  {
    id: 'emp-003',
    userId: 'user-003',
    fullName: 'Ibrahim Koroma',
    title: 'Head of Hydrological department',
    department: 'hydrological',
    phone: '+232 76 333333',
    email: 'hod.hydro@nwrma.gov.sl',
    hiredAt: new Date('2023-02-01'),
    status: 'active',
  },
  {
    id: 'emp-004',
    userId: 'user-004',
    fullName: 'Aminata Bangura',
    title: 'Head of Borehole Registry',
    department: 'boreholes',
    phone: '+232 76 444444',
    email: 'hod.boreholes@nwrma.gov.sl',
    hiredAt: new Date('2023-02-01'),
    status: 'active',
  },
  {
    id: 'emp-005',
    userId: 'user-005',
    fullName: 'Samuel Conteh',
    title: 'Head of Water Quality',
    department: 'hydrological',
    phone: '+232 76 555555',
    email: 'hod.wq@nwrma.gov.sl',
    hiredAt: new Date('2023-02-01'),
    status: 'active',
  },
  {
    id: 'emp-006',
    userId: 'user-006',
    fullName: 'Mariama Jalloh',
    title: 'Chief Financial Officer',
    department: 'financial',
    phone: '+232 76 666666',
    email: 'hod.finance@nwrma.gov.sl',
    hiredAt: new Date('2023-02-01'),
    status: 'active',
  },
  {
    id: 'emp-007',
    userId: 'user-007',
    fullName: 'Abu Bakarr Turay',
    title: 'Head of Human Resources',
    department: 'hr',
    phone: '+232 76 777777',
    email: 'hod.hr@nwrma.gov.sl',
    hiredAt: new Date('2023-02-01'),
    status: 'active',
  },
  {
    id: 'emp-008',
    userId: 'user-008',
    fullName: 'Isatu Mansaray',
    title: 'Hydrological Officer',
    department: 'hydrological',
    phone: '+232 76 888888',
    email: 'staff.hydro@nwrma.gov.sl',
    hiredAt: new Date('2023-03-15'),
    status: 'active',
  },
]

// Leave Requests
export const leaveRequests: LeaveRequest[] = [
  {
    id: 'lv-001',
    employeeId: 'emp-008',
    employeeName: 'Isatu Mansaray',
    start: new Date('2024-04-01'),
    end: new Date('2024-04-05'),
    type: 'annual',
    status: 'hod_review',
    approverId: null,
    approverName: null,
    comment: 'Family vacation',
    createdAt: new Date('2024-03-10'),
  },
  {
    id: 'lv-002',
    employeeId: 'emp-003',
    employeeName: 'Ibrahim Koroma',
    start: new Date('2024-03-20'),
    end: new Date('2024-03-22'),
    type: 'sick',
    status: 'approved',
    approverId: 'user-002',
    approverName: 'Dr. Fatmata Sesay',
    comment: 'Medical appointment',
    createdAt: new Date('2024-03-18'),
  },
  {
    id: 'lv-003',
    employeeId: 'emp-001',
    employeeName: 'Mohamed Kamara',
    start: new Date('2024-06-01'),
    end: new Date('2024-06-02'),
    type: 'annual',
    status: 'dg_review',
    approverId: null,
    approverName: null,
    comment: 'Personal travel (HoD endorsed)',
    createdAt: new Date('2024-05-28'),
  },
]

// Assets
export const assets: Asset[] = [
  {
    id: 'ast-001',
    tag: 'NWRMA-VEH-001',
    name: 'Toyota Land Cruiser',
    category: 'Vehicle',
    custodianEmployeeId: 'emp-003',
    custodianName: 'Ibrahim Koroma',
    location: 'Hydrological Dept. Garage',
    acquiredAt: new Date('2023-06-15'),
    cost: 850000000,
    status: 'in_use',
  },
  {
    id: 'ast-002',
    tag: 'NWRMA-LAB-001',
    name: 'Water Quality Analyzer',
    category: 'Laboratory Equipment',
    custodianEmployeeId: 'emp-005',
    custodianName: 'Samuel Conteh',
    location: 'Main Laboratory',
    acquiredAt: new Date('2023-08-01'),
    cost: 250000000,
    status: 'in_use',
  },
  {
    id: 'ast-003',
    tag: 'NWRMA-IT-001',
    name: 'Dell Server',
    category: 'IT Equipment',
    custodianEmployeeId: 'emp-001',
    custodianName: 'Mohamed Kamara',
    location: 'Server Room',
    acquiredAt: new Date('2023-01-20'),
    cost: 150000000,
    status: 'in_use',
  },
]

// Public Applications
export const boreholeLicenseApplications: BoreholeLicenseApplication[] = [
  {
    id: 'bla-001',
    reference: 'BLA-2026-0001',
    status: 'submitted',
    applicantName: 'James Koroma',
    applicantEmail: 'jkoroma@koromadrilling.sl',
    organisationName: 'Koroma Drilling Services Ltd',
    submittedAt: new Date('2026-03-10'),
    companyName: 'Koroma Drilling Services Ltd',
    regNumber: 'SL-REG-2019-8842',
    email: 'info@koromadrilling.sl',
    phone: '+232 76 442 118',
    address: '12 Wilkinson Road, Freetown',
    contactName: 'James Koroma',
    contactRole: 'Managing Director',
    contactEmail: 'jkoroma@koromadrilling.sl',
    contactPhone: '+232 76 442 119',
    district: 'Western Area Urban',
    rigCount: '2',
    equipmentDescription:
      'Two truck-mounted rotary rigs, support vehicles including water bowser and compressor truck.',
    leadHydrogeologist: 'Dr. Aminata Sesay — MSc Hydrogeology',
    qualifiedDrillersCount: '4',
    documents: (() => {
      const docs = emptyDocumentMetaSlots()
      docs.businessRegistration = [{ id: 'demo-001-biz', name: 'koroma-business-registration.pdf', size: 245_000 }]
      docs.certificateOfIncorporation = [...docs.businessRegistration]
      docs.machineLifeCards = [
        { id: 'demo-001-rig', name: 'rig-01-life-card.pdf', size: 180_000 },
        { id: 'demo-001-veh', name: 'support-vehicle-life-cards.pdf', size: 210_000 },
      ]
      docs.slrsaProof = [...docs.machineLifeCards]
      docs.personnelCvs = [
        { id: 'demo-001-cv1', name: 'sesay-hydrogeologist-cv.pdf', size: 320_000 },
        { id: 'demo-001-cv2', name: 'drilling-crew-cvs-bundle.pdf', size: 890_000 },
      ]
      docs.annex2PersonnelCvs = [...docs.personnelCvs]
      return docs
    })(),
    reviewNote: null,
    reviewedAt: null,
    siteInspectionDate: null,
    siteInspectionNotes: null,
    technicalReportSummary: null,
    lastEmailSentAt: null,
  },
  {
    id: 'bla-002',
    reference: 'BLA-2026-0002',
    status: 'under_review',
    applicantName: 'Mariama Bangura',
    applicantEmail: 'licensing@sierradrill.sl',
    organisationName: 'Sierra Drill Co.',
    submittedAt: new Date('2026-03-12'),
    companyName: 'Sierra Drill Co.',
    regNumber: 'SL-REG-2021-3310',
    email: 'licensing@sierradrill.sl',
    phone: '+232 30 555 902',
    address: '45 Spur Road, Wilberforce, Freetown',
    contactName: 'Mariama Bangura',
    contactRole: 'Operations Manager',
    contactEmail: 'm.bangura@sierradrill.sl',
    contactPhone: '+232 77 201 445',
    district: 'Bo',
    rigCount: '1',
    equipmentDescription: 'Single deep-well rig with mud pump; one flatbed support vehicle.',
    leadHydrogeologist: 'Ibrahim Kargbo — BSc Geology',
    qualifiedDrillersCount: '3',
    documents: (() => {
      const docs = emptyDocumentMetaSlots()
      docs.businessRegistration = [{ id: 'demo-002-biz', name: 'sierra-drill-registration.pdf', size: 198_000 }]
      docs.certificateOfIncorporation = [...docs.businessRegistration]
      docs.machineLifeCards = [{ id: 'demo-002-rig', name: 'rig-life-card-2026.jpg', size: 1_240_000 }]
      docs.slrsaProof = [...docs.machineLifeCards]
      docs.personnelCvs = [{ id: 'demo-002-cv', name: 'personnel-cvs-complete.pdf', size: 1_560_000 }]
      docs.annex2PersonnelCvs = [...docs.personnelCvs]
      return docs
    })(),
    reviewNote: 'Awaiting site inspection scheduling.',
    reviewedAt: new Date('2026-03-13'),
    siteInspectionDate: null,
    siteInspectionNotes: null,
    technicalReportSummary: null,
    lastEmailSentAt: null,
  },
  {
    id: 'bla-003',
    reference: 'BLA-2025-0012',
    status: 'approved',
    applicantName: 'Freetown Municipal Council',
    applicantEmail: 'water@fmc.gov.sl',
    organisationName: 'Freetown Municipal Council',
    submittedAt: new Date('2025-11-20'),
    companyName: 'Freetown Municipal Council — Water Division',
    regNumber: 'GOV-FMC-001',
    email: 'water@fmc.gov.sl',
    phone: '+232 22 223 456',
    address: 'City Hall, Wallace Johnson Street, Freetown',
    contactName: 'Samuel Turay',
    contactRole: 'Chief Water Engineer',
    contactEmail: 's.turay@fmc.gov.sl',
    contactPhone: '+232 76 880 012',
    district: 'Western Area Urban',
    rigCount: '3',
    equipmentDescription: 'Municipal drilling fleet with three rigs and full support logistics.',
    leadHydrogeologist: 'Eng. Patricia Cole — Chartered Hydrogeologist',
    qualifiedDrillersCount: '8',
    documents: (() => {
      const docs = emptyDocumentMetaSlots()
      docs.businessRegistration = [{ id: 'demo-003-biz', name: 'fmc-mandate-letter.pdf', size: 156_000 }]
      docs.certificateOfIncorporation = [...docs.businessRegistration]
      docs.machineLifeCards = [{ id: 'demo-003-rig', name: 'fleet-life-cards-2025.pdf', size: 2_100_000 }]
      docs.slrsaProof = [...docs.machineLifeCards]
      docs.personnelCvs = [{ id: 'demo-003-cv', name: 'fmc-technical-roster.pdf', size: 3_400_000 }]
      docs.annex2PersonnelCvs = [...docs.personnelCvs]
      return docs
    })(),
    reviewNote: 'Approved after site verification.',
    reviewedAt: new Date('2025-12-05'),
    siteInspectionDate: '2025-11-28',
    siteInspectionNotes: 'Fleet verified at Wilberforce yard.',
    technicalReportSummary: 'Equipment adequate; recommend licence grant.',
    lastEmailSentAt: null,
  },
]

export const waterQualityPublicCases: WaterQualityPublicCase[] = [
  {
    id: 'wq-pub-001',
    reference: 'WQPC-2024-0001',
    status: 'completed',
    applicantName: 'John Smith',
    applicantEmail: 'jsmith@email.com',
    siteAddress: '45 Hill Station, Freetown',
    testsRequested: ['pH', 'Turbidity', 'Iron', 'Manganese'],
    paymentStatus: 'paid',
    paymentRef: 'PAY-2024-0001',
    createdAt: new Date('2024-03-01'),
  },
  {
    id: 'wq-pub-002',
    reference: 'WQPC-2024-0002',
    status: 'payment_pending',
    applicantName: 'Mary Johnson',
    applicantEmail: 'mjohnson@email.com',
    siteAddress: '12 Aberdeen Road, Freetown',
    testsRequested: ['Full Panel'],
    paymentStatus: 'pending',
    paymentRef: null,
    createdAt: new Date('2024-03-14'),
  },
]

// Notifications
export const notifications: Notification[] = [
  {
    id: 'notif-001',
    userId: 'user-001',
    title: 'New Requisition',
    message: 'A new requisition REQ-004 requires your attention',
    type: 'info',
    read: false,
    link: '/finance/requisitions',
    createdAt: new Date('2024-03-15T10:00:00'),
    scopeDepartment: 'financial',
  },
  {
    id: 'notif-002',
    userId: 'user-001',
    title: 'Requisition Approved',
    message: 'Requisition REQ-003 has been approved by the DG',
    type: 'success',
    read: true,
    link: '/finance/requisitions',
    createdAt: new Date('2024-02-28T14:30:00'),
    scopeDepartment: 'financial',
  },
  {
    id: 'notif-003',
    userId: 'user-001',
    title: 'Critical Lab Request',
    message: 'UNICEF has submitted a critical water quality request',
    type: 'warning',
    read: false,
    link: '/water-quality/requests',
    createdAt: new Date('2024-03-14T09:00:00'),
    scopeDepartment: 'hydrological',
  },
]
