/** Public site image paths under /nwrma-site/ */
export const NWRMA_ASSETS = {
  heroHome: '/nwrma-site/hero-home.jpg',
  bannerDefault: '/nwrma-site/banner-default.jpg',
  bannerAbout: '/nwrma-site/banner-about.jpg',
  aboutSide: '/nwrma-site/about-side.jpg',
  homeAboutRiver: '/nwrma-site/home-about-river.jpg',
  onlineResourcesBg: '/nwrma-site/online-resources-bg.jpg',
  newsWaterBg: '/nwrma-site/news-water-bg.jpg',
  tileData: '/nwrma-site/tile-data.jpg',
  tileMaps: '/nwrma-site/tile-maps.jpg',
  tilePublications: '/nwrma-site/tile-publications.jpg',
  deptPlanning: '/nwrma-site/dept-planning.jpg',
  deptLegal: '/nwrma-site/dept-legal.jpg',
  deptAdmin: '/nwrma-site/dept-admin.jpg',
  deptFinance: '/nwrma-site/dept-finance.jpg',
  deptHydro: '/nwrma-site/dept-hydro.jpg',
  logo: '/nwrma-site/logo.svg',
  iconRegulation: '/nwrma-site/icons/regulation.svg',
  iconProtection: '/nwrma-site/icons/protection.svg',
  iconPublicInfo: '/nwrma-site/icons/public-info.svg',
  iconClimate: '/nwrma-site/icons/climate.svg',
  newsHoliday: '/nwrma-site/dept-planning.jpg',
  newsParliament: '/nwrma-site/dept-admin.jpg',
  newsIwmi: '/nwrma-site/dept-finance.jpg',
} as const
